- name: Create fstab
  blockinfile:
    path: /etc/fstab
    block: |
      /dev/sda2 /boot ext4 noauto,noatime 1 2
      /dev/sda3 / ext4 noatime 0 1

- name: Install grub to /dev/sda
  shell: grub-install /dev/sda >> /makelog

- name: Set grub timeout to 0
  lineinfile:
    path: /etc/default/grub
    line: GRUB_TIMEOUT=0

- name: Generate grub configuration file
  shell: grub-mkconfig -o /boot/grub/grub.cfg >> /makelog
